flyway:
  migration:
    options:
      - migrate

spring:
  datasource:
    url: jdbc:mysql://${database.host:localhost}:${database.port:3306}/${database.schema:virta_task_db}
    username: ${database.user:root}
    password: ${database.password:gor123}
    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:scripts
    url: jdbc:mysql://${database.host:localhost}:${database.port:3306}/${database.schema:virta_task_db}
    password: ${database.password:gor123}
    user: ${database.user:root}
    driver-class-name: com.mysql.cj.jdbc.Driver