/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.task;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ApiRunner {

    public static void main(String[] args) {

        SpringApplication.run(ApiRunner.class, args);

    }

}